// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQ4FLQjpcJj_1WXXeGfcPHBrLj7qNGWU',
    appId: '1:885390230612:web:652aca0a81955385e4d9c1',
    messagingSenderId: '885390230612',
    projectId: 'primeval-rune-471911-g6',
    authDomain: 'primeval-rune-471911-g6.firebaseapp.com',
    storageBucket: 'primeval-rune-471911-g6.firebasestorage.app',
    measurementId: 'G-6PTDLVDVDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOPEoNxB-CrsXtTXdTpXgkp55Az5I0ao',
    appId: '1:885390230612:android:1efb1ee096220899e4d9c1',
    messagingSenderId: '885390230612',
    projectId: 'primeval-rune-471911-g6',
    storageBucket: 'primeval-rune-471911-g6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaLPh7VQ-IoMW6S7yxNJ_HNuD16HIO1Es',
    appId: '1:885390230612:ios:6f89a2363e0f069fe4d9c1',
    messagingSenderId: '885390230612',
    projectId: 'primeval-rune-471911-g6',
    storageBucket: 'primeval-rune-471911-g6.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

}