// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcARkwcgQqYx0KMyM0V8ely5yAvGQSwnE',
    appId: '1:516749431216:web:6a4cf10a9b1353096a8675',
    messagingSenderId: '516749431216',
    projectId: 'go-trike-14d3f',
    authDomain: 'go-trike-14d3f.firebaseapp.com',
    storageBucket: 'go-trike-14d3f.firebasestorage.app',
    measurementId: 'G-V3FF7FP9VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAclw7DcrXMH8xY7bAhZx7W7F-jcLhYJM',
    appId: '1:516749431216:android:7093ca3f2cfee8cb6a8675',
    messagingSenderId: '516749431216',
    projectId: 'go-trike-14d3f',
    storageBucket: 'go-trike-14d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzzgb_z-TmnKl1de2ns_DdMzBY0Mx5r7A',
    appId: '1:516749431216:ios:427add6d47f2ee6b6a8675',
    messagingSenderId: '516749431216',
    projectId: 'go-trike-14d3f',
    storageBucket: 'go-trike-14d3f.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

}